import type { BrandingResolved } from './brandingApi';

/**
 * Canonical Mamba seller-facing theme (P&L “muted cards”, semantic profit/loss).
 * Used when no tenant_branding row exists, agency UI “Platform Default”, and SellerBrandingProvider fallback.
 *
 * Keep server `PLATFORM_THEME_MERGE_DEFAULTS` in `server/src/routes/branding.routes.ts` aligned with these values (snake_case).
 */
export const PLATFORM_BRANDING_FORM_THEME_ONLY = {
    primaryColor: '#ec4899',
    secondaryColor: '#6366f1',
    bgColor: '#111827',
    sidebarBgColor: '#111827',
    sidebarBorderColor: '#1f2937',
    cardBgColor: '#ffffff06',
    cardBorderColor: '#ffffff1a',
    textColor: '#ffffff',
    textMutedColor: '#6b7280',
    btnTextColor: '#ffffff',
    cardHoverColor: '#ffffff12',
    interactiveHoverBg: '#ffffff12',
    interactiveFocusRing: '#ec489955',
    successBg: '#10b9811f',
    successText: '#6ee7b7',
    successBorder: '#10b98166',
    warningBg: '#f59e0b1f',
    warningText: '#fcd34d',
    warningBorder: '#f59e0b66',
    dangerBg: '#ef44441f',
    dangerText: '#fca5a5',
    dangerBorder: '#ef444466',
    infoBg: '#3b82f61f',
    infoText: '#93c5fd',
    infoBorder: '#3b82f666',
    profitColor: '#34d399',
    lossColor: '#f87171',
    primaryCardBg: '#111827',
    /** Neutral gray border — avoids accent “Skittles” on metric tiles (matches P&L secondary cards). */
    primaryCardBorder: '#374151',
    secondaryCardBg: '#1f2937',
    secondaryCardBorder: '#374151',
    toastSuccessBg: '#052e22',
    toastSuccessBorder: '#10b98173',
    toastSuccessIcon: '#34d399',
    toastErrorBg: '#3f1010',
    toastErrorBorder: '#ef444473',
    toastErrorIcon: '#f87171',
    toastInfoBg: '#0f1f3f',
    toastInfoBorder: '#3b82f673',
    toastInfoIcon: '#60a5fa',
    toastWarningBg: '#3b2208',
    toastWarningBorder: '#f59e0b73',
    toastWarningIcon: '#fbbf24',
    chartGrid: '#33415566',
    chartAxis: '#94a3b8',
    chartSeries1: '#ec4899',
    chartSeries2: '#6366f1',
    chartSeries3: '#22c55e',
    chartSeries4: '#eab308',
    chartSeries5: '#06b6d4',
    chartSeries6: '#f97316',
    chartPositive: '#34d399',
    chartNegative: '#f87171',
    chartNeutral: '#64748b',
} as const;

/** Same palette as {@link PLATFORM_BRANDING_FORM_THEME_ONLY}, shaped for BrandingResolved / CSS vars. */
export const PLATFORM_BRANDING_RESOLVED_DEFAULT: BrandingResolved = {
    agencyTenantId: null,
    source: 'platform_default',
    primaryColor: PLATFORM_BRANDING_FORM_THEME_ONLY.primaryColor,
    secondaryColor: PLATFORM_BRANDING_FORM_THEME_ONLY.secondaryColor,
    bgColor: PLATFORM_BRANDING_FORM_THEME_ONLY.bgColor,
    sidebarBgColor: PLATFORM_BRANDING_FORM_THEME_ONLY.sidebarBgColor,
    sidebarBorderColor: PLATFORM_BRANDING_FORM_THEME_ONLY.sidebarBorderColor,
    cardBgColor: PLATFORM_BRANDING_FORM_THEME_ONLY.cardBgColor,
    cardBorderColor: PLATFORM_BRANDING_FORM_THEME_ONLY.cardBorderColor,
    textColor: PLATFORM_BRANDING_FORM_THEME_ONLY.textColor,
    textMutedColor: PLATFORM_BRANDING_FORM_THEME_ONLY.textMutedColor,
    btnTextColor: PLATFORM_BRANDING_FORM_THEME_ONLY.btnTextColor,
    cardHoverColor: PLATFORM_BRANDING_FORM_THEME_ONLY.cardHoverColor,
    interactiveHoverBg: PLATFORM_BRANDING_FORM_THEME_ONLY.interactiveHoverBg,
    interactiveFocusRing: PLATFORM_BRANDING_FORM_THEME_ONLY.interactiveFocusRing,
    successBg: PLATFORM_BRANDING_FORM_THEME_ONLY.successBg,
    successText: PLATFORM_BRANDING_FORM_THEME_ONLY.successText,
    successBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.successBorder,
    warningBg: PLATFORM_BRANDING_FORM_THEME_ONLY.warningBg,
    warningText: PLATFORM_BRANDING_FORM_THEME_ONLY.warningText,
    warningBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.warningBorder,
    dangerBg: PLATFORM_BRANDING_FORM_THEME_ONLY.dangerBg,
    dangerText: PLATFORM_BRANDING_FORM_THEME_ONLY.dangerText,
    dangerBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.dangerBorder,
    infoBg: PLATFORM_BRANDING_FORM_THEME_ONLY.infoBg,
    infoText: PLATFORM_BRANDING_FORM_THEME_ONLY.infoText,
    infoBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.infoBorder,
    profitColor: PLATFORM_BRANDING_FORM_THEME_ONLY.profitColor,
    lossColor: PLATFORM_BRANDING_FORM_THEME_ONLY.lossColor,
    primaryCardBg: PLATFORM_BRANDING_FORM_THEME_ONLY.primaryCardBg,
    primaryCardBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.primaryCardBorder,
    secondaryCardBg: PLATFORM_BRANDING_FORM_THEME_ONLY.secondaryCardBg,
    secondaryCardBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.secondaryCardBorder,
    toastSuccessBg: PLATFORM_BRANDING_FORM_THEME_ONLY.toastSuccessBg,
    toastSuccessBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.toastSuccessBorder,
    toastSuccessIcon: PLATFORM_BRANDING_FORM_THEME_ONLY.toastSuccessIcon,
    toastErrorBg: PLATFORM_BRANDING_FORM_THEME_ONLY.toastErrorBg,
    toastErrorBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.toastErrorBorder,
    toastErrorIcon: PLATFORM_BRANDING_FORM_THEME_ONLY.toastErrorIcon,
    toastInfoBg: PLATFORM_BRANDING_FORM_THEME_ONLY.toastInfoBg,
    toastInfoBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.toastInfoBorder,
    toastInfoIcon: PLATFORM_BRANDING_FORM_THEME_ONLY.toastInfoIcon,
    toastWarningBg: PLATFORM_BRANDING_FORM_THEME_ONLY.toastWarningBg,
    toastWarningBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.toastWarningBorder,
    toastWarningIcon: PLATFORM_BRANDING_FORM_THEME_ONLY.toastWarningIcon,
    chartGrid: PLATFORM_BRANDING_FORM_THEME_ONLY.chartGrid,
    chartAxis: PLATFORM_BRANDING_FORM_THEME_ONLY.chartAxis,
    chartSeries1: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries1,
    chartSeries2: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries2,
    chartSeries3: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries3,
    chartSeries4: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries4,
    chartSeries5: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries5,
    chartSeries6: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries6,
    chartPositive: PLATFORM_BRANDING_FORM_THEME_ONLY.chartPositive,
    chartNegative: PLATFORM_BRANDING_FORM_THEME_ONLY.chartNegative,
    chartNeutral: PLATFORM_BRANDING_FORM_THEME_ONLY.chartNeutral,
    displayName: 'Mamba',
    emailSenderName: null,
    emailSenderAddress: null,
    customPresets: [],
    updatedAt: null,
    logoSignedUrl: null,
};
