import type { BrandingResolved } from './brandingApi';

/**
 * Official Mamba dark theme (9-color palette + derived semantics).
 * Used when no tenant_branding row exists, agency “Mamba (Official)” preset, and SellerBrandingProvider fallback.
 *
 * Swatches: Mamba Green #28D99E, Deep #1FA97C, Neon #49FFB7, bg #06141A, panel #0D1B21,
 * card #13262E, border #1F3A43, text #E6F3F1, muted #8CAFB3.
 *
 * Keep server `PLATFORM_THEME_MERGE_DEFAULTS` in `server/src/routes/branding.routes.ts` aligned (snake_case).
 */
export const PLATFORM_BRANDING_FORM_THEME_ONLY = {
    primaryColor: '#28D99E',
    secondaryColor: '#1FA97C',
    bgColor: '#06141A',
    sidebarBgColor: '#0D1B21',
    sidebarBorderColor: '#1F3A43',
    cardBgColor: '#13262E',
    cardBorderColor: '#1F3A43',
    textColor: '#E6F3F1',
    textMutedColor: '#8CAFB3',
    /** Contrast on primary fills — dark on Mamba Green. */
    btnTextColor: '#06141A',
    cardHoverColor: '#ffffff14',
    interactiveHoverBg: '#ffffff0d',
    interactiveFocusRing: '#28D99E99',
    successBg: '#28D99E1f',
    successText: '#49FFB7',
    successBorder: '#28D99E66',
    warningBg: '#f59e0b1f',
    warningText: '#fcd34d',
    warningBorder: '#f59e0b66',
    dangerBg: '#ef44441f',
    dangerText: '#fca5a5',
    dangerBorder: '#ef444466',
    infoBg: '#06b6d41f',
    infoText: '#67e8f9',
    infoBorder: '#22d3ee66',
    profitColor: '#49FFB7',
    lossColor: '#f87171',
    primaryCardBg: '#0D1B21',
    primaryCardBorder: '#1F3A43',
    secondaryCardBg: '#13262E',
    secondaryCardBorder: '#1F3A43',
    toastSuccessBg: '#041816',
    toastSuccessBorder: '#28D99E73',
    toastSuccessIcon: '#49FFB7',
    toastErrorBg: '#3f1010',
    toastErrorBorder: '#ef444473',
    toastErrorIcon: '#f87171',
    toastInfoBg: '#082f3a',
    toastInfoBorder: '#22d3ee73',
    toastInfoIcon: '#67e8f9',
    toastWarningBg: '#3b2208',
    toastWarningBorder: '#f59e0b73',
    toastWarningIcon: '#fbbf24',
    chartGrid: '#1F3A4366',
    chartAxis: '#8CAFB3',
    chartSeries1: '#28D99E',
    chartSeries2: '#49FFB7',
    chartSeries3: '#1FA97C',
    chartSeries4: '#eab308',
    chartSeries5: '#f97316',
    chartSeries6: '#a78bfa',
    chartPositive: '#49FFB7',
    chartNegative: '#f87171',
    chartNeutral: '#8CAFB3',
} as const;

/** Same palette as {@link PLATFORM_BRANDING_FORM_THEME_ONLY}, shaped for BrandingResolved / CSS vars. */
export const PLATFORM_BRANDING_RESOLVED_DEFAULT: BrandingResolved = {
    agencyTenantId: null,
    source: 'platform_default',
    primaryColor: PLATFORM_BRANDING_FORM_THEME_ONLY.primaryColor,
    secondaryColor: PLATFORM_BRANDING_FORM_THEME_ONLY.secondaryColor,
    bgColor: PLATFORM_BRANDING_FORM_THEME_ONLY.bgColor,
    sidebarBgColor: PLATFORM_BRANDING_FORM_THEME_ONLY.sidebarBgColor,
    sidebarBorderColor: PLATFORM_BRANDING_FORM_THEME_ONLY.sidebarBorderColor,
    cardBgColor: PLATFORM_BRANDING_FORM_THEME_ONLY.cardBgColor,
    cardBorderColor: PLATFORM_BRANDING_FORM_THEME_ONLY.cardBorderColor,
    textColor: PLATFORM_BRANDING_FORM_THEME_ONLY.textColor,
    textMutedColor: PLATFORM_BRANDING_FORM_THEME_ONLY.textMutedColor,
    btnTextColor: PLATFORM_BRANDING_FORM_THEME_ONLY.btnTextColor,
    cardHoverColor: PLATFORM_BRANDING_FORM_THEME_ONLY.cardHoverColor,
    interactiveHoverBg: PLATFORM_BRANDING_FORM_THEME_ONLY.interactiveHoverBg,
    interactiveFocusRing: PLATFORM_BRANDING_FORM_THEME_ONLY.interactiveFocusRing,
    successBg: PLATFORM_BRANDING_FORM_THEME_ONLY.successBg,
    successText: PLATFORM_BRANDING_FORM_THEME_ONLY.successText,
    successBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.successBorder,
    warningBg: PLATFORM_BRANDING_FORM_THEME_ONLY.warningBg,
    warningText: PLATFORM_BRANDING_FORM_THEME_ONLY.warningText,
    warningBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.warningBorder,
    dangerBg: PLATFORM_BRANDING_FORM_THEME_ONLY.dangerBg,
    dangerText: PLATFORM_BRANDING_FORM_THEME_ONLY.dangerText,
    dangerBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.dangerBorder,
    infoBg: PLATFORM_BRANDING_FORM_THEME_ONLY.infoBg,
    infoText: PLATFORM_BRANDING_FORM_THEME_ONLY.infoText,
    infoBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.infoBorder,
    profitColor: PLATFORM_BRANDING_FORM_THEME_ONLY.profitColor,
    lossColor: PLATFORM_BRANDING_FORM_THEME_ONLY.lossColor,
    primaryCardBg: PLATFORM_BRANDING_FORM_THEME_ONLY.primaryCardBg,
    primaryCardBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.primaryCardBorder,
    secondaryCardBg: PLATFORM_BRANDING_FORM_THEME_ONLY.secondaryCardBg,
    secondaryCardBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.secondaryCardBorder,
    toastSuccessBg: PLATFORM_BRANDING_FORM_THEME_ONLY.toastSuccessBg,
    toastSuccessBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.toastSuccessBorder,
    toastSuccessIcon: PLATFORM_BRANDING_FORM_THEME_ONLY.toastSuccessIcon,
    toastErrorBg: PLATFORM_BRANDING_FORM_THEME_ONLY.toastErrorBg,
    toastErrorBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.toastErrorBorder,
    toastErrorIcon: PLATFORM_BRANDING_FORM_THEME_ONLY.toastErrorIcon,
    toastInfoBg: PLATFORM_BRANDING_FORM_THEME_ONLY.toastInfoBg,
    toastInfoBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.toastInfoBorder,
    toastInfoIcon: PLATFORM_BRANDING_FORM_THEME_ONLY.toastInfoIcon,
    toastWarningBg: PLATFORM_BRANDING_FORM_THEME_ONLY.toastWarningBg,
    toastWarningBorder: PLATFORM_BRANDING_FORM_THEME_ONLY.toastWarningBorder,
    toastWarningIcon: PLATFORM_BRANDING_FORM_THEME_ONLY.toastWarningIcon,
    chartGrid: PLATFORM_BRANDING_FORM_THEME_ONLY.chartGrid,
    chartAxis: PLATFORM_BRANDING_FORM_THEME_ONLY.chartAxis,
    chartSeries1: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries1,
    chartSeries2: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries2,
    chartSeries3: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries3,
    chartSeries4: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries4,
    chartSeries5: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries5,
    chartSeries6: PLATFORM_BRANDING_FORM_THEME_ONLY.chartSeries6,
    chartPositive: PLATFORM_BRANDING_FORM_THEME_ONLY.chartPositive,
    chartNegative: PLATFORM_BRANDING_FORM_THEME_ONLY.chartNegative,
    chartNeutral: PLATFORM_BRANDING_FORM_THEME_ONLY.chartNeutral,
    displayName: 'Mamba',
    emailSenderName: null,
    emailSenderAddress: null,
    customPresets: [],
    updatedAt: null,
    logoSignedUrl: null,
};
