-- Extend tenant_branding_apply_patch RPC to cover semantic token columns.

DROP FUNCTION IF EXISTS public.tenant_branding_apply_patch(
    uuid, text, text, text, text, text, text, text, text, text, text, text, text, text, jsonb, text
);

CREATE OR REPLACE FUNCTION public.tenant_branding_apply_patch(
    p_tenant_id uuid,
    p_primary_color text,
    p_secondary_color text,
    p_bg_color text,
    p_sidebar_bg_color text,
    p_sidebar_border_color text,
    p_card_bg_color text,
    p_card_border_color text,
    p_text_color text,
    p_text_muted_color text,
    p_btn_text_color text,
    p_card_hover_color text,
    p_interactive_hover_bg text,
    p_interactive_focus_ring text,
    p_success_bg text,
    p_success_text text,
    p_success_border text,
    p_warning_bg text,
    p_warning_text text,
    p_warning_border text,
    p_danger_bg text,
    p_danger_text text,
    p_danger_border text,
    p_info_bg text,
    p_info_text text,
    p_info_border text,
    p_profit_color text,
    p_loss_color text,
    p_primary_card_bg text,
    p_primary_card_border text,
    p_secondary_card_bg text,
    p_secondary_card_border text,
    p_toast_success_bg text,
    p_toast_success_border text,
    p_toast_success_icon text,
    p_toast_error_bg text,
    p_toast_error_border text,
    p_toast_error_icon text,
    p_toast_info_bg text,
    p_toast_info_border text,
    p_toast_info_icon text,
    p_toast_warning_bg text,
    p_toast_warning_border text,
    p_toast_warning_icon text,
    p_chart_grid text,
    p_chart_axis text,
    p_chart_series_1 text,
    p_chart_series_2 text,
    p_chart_series_3 text,
    p_chart_series_4 text,
    p_chart_series_5 text,
    p_chart_series_6 text,
    p_chart_positive text,
    p_chart_negative text,
    p_chart_neutral text,
    p_display_name text,
    p_email_sender_name text,
    p_email_sender_address text,
    p_custom_presets jsonb,
    p_logo_object_path text
)
RETURNS SETOF public.tenant_branding
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    INSERT INTO public.tenant_branding (
        tenant_id, primary_color, secondary_color,
        bg_color, sidebar_bg_color, sidebar_border_color, card_bg_color, card_border_color,
        text_color, text_muted_color, btn_text_color,
        card_hover_color, interactive_hover_bg, interactive_focus_ring,
        success_bg, success_text, success_border,
        warning_bg, warning_text, warning_border,
        danger_bg, danger_text, danger_border,
        info_bg, info_text, info_border,
        profit_color, loss_color,
        primary_card_bg, primary_card_border, secondary_card_bg, secondary_card_border,
        toast_success_bg, toast_success_border, toast_success_icon,
        toast_error_bg, toast_error_border, toast_error_icon,
        toast_info_bg, toast_info_border, toast_info_icon,
        toast_warning_bg, toast_warning_border, toast_warning_icon,
        chart_grid, chart_axis, chart_series_1, chart_series_2, chart_series_3, chart_series_4, chart_series_5, chart_series_6,
        chart_positive, chart_negative, chart_neutral,
        display_name, email_sender_name, email_sender_address, custom_presets, logo_object_path
    )
    VALUES (
        p_tenant_id, p_primary_color, p_secondary_color,
        p_bg_color, p_sidebar_bg_color, p_sidebar_border_color, p_card_bg_color, p_card_border_color,
        p_text_color, p_text_muted_color, p_btn_text_color,
        p_card_hover_color, p_interactive_hover_bg, p_interactive_focus_ring,
        p_success_bg, p_success_text, p_success_border,
        p_warning_bg, p_warning_text, p_warning_border,
        p_danger_bg, p_danger_text, p_danger_border,
        p_info_bg, p_info_text, p_info_border,
        p_profit_color, p_loss_color,
        p_primary_card_bg, p_primary_card_border, p_secondary_card_bg, p_secondary_card_border,
        p_toast_success_bg, p_toast_success_border, p_toast_success_icon,
        p_toast_error_bg, p_toast_error_border, p_toast_error_icon,
        p_toast_info_bg, p_toast_info_border, p_toast_info_icon,
        p_toast_warning_bg, p_toast_warning_border, p_toast_warning_icon,
        p_chart_grid, p_chart_axis, p_chart_series_1, p_chart_series_2, p_chart_series_3, p_chart_series_4, p_chart_series_5, p_chart_series_6,
        p_chart_positive, p_chart_negative, p_chart_neutral,
        p_display_name, p_email_sender_name, p_email_sender_address, COALESCE(p_custom_presets, '[]'::jsonb), p_logo_object_path
    )
    ON CONFLICT (tenant_id) DO UPDATE SET
        primary_color = EXCLUDED.primary_color,
        secondary_color = EXCLUDED.secondary_color,
        bg_color = EXCLUDED.bg_color,
        sidebar_bg_color = EXCLUDED.sidebar_bg_color,
        sidebar_border_color = EXCLUDED.sidebar_border_color,
        card_bg_color = EXCLUDED.card_bg_color,
        card_border_color = EXCLUDED.card_border_color,
        text_color = EXCLUDED.text_color,
        text_muted_color = EXCLUDED.text_muted_color,
        btn_text_color = EXCLUDED.btn_text_color,
        card_hover_color = EXCLUDED.card_hover_color,
        interactive_hover_bg = EXCLUDED.interactive_hover_bg,
        interactive_focus_ring = EXCLUDED.interactive_focus_ring,
        success_bg = EXCLUDED.success_bg,
        success_text = EXCLUDED.success_text,
        success_border = EXCLUDED.success_border,
        warning_bg = EXCLUDED.warning_bg,
        warning_text = EXCLUDED.warning_text,
        warning_border = EXCLUDED.warning_border,
        danger_bg = EXCLUDED.danger_bg,
        danger_text = EXCLUDED.danger_text,
        danger_border = EXCLUDED.danger_border,
        info_bg = EXCLUDED.info_bg,
        info_text = EXCLUDED.info_text,
        info_border = EXCLUDED.info_border,
        profit_color = EXCLUDED.profit_color,
        loss_color = EXCLUDED.loss_color,
        primary_card_bg = EXCLUDED.primary_card_bg,
        primary_card_border = EXCLUDED.primary_card_border,
        secondary_card_bg = EXCLUDED.secondary_card_bg,
        secondary_card_border = EXCLUDED.secondary_card_border,
        toast_success_bg = EXCLUDED.toast_success_bg,
        toast_success_border = EXCLUDED.toast_success_border,
        toast_success_icon = EXCLUDED.toast_success_icon,
        toast_error_bg = EXCLUDED.toast_error_bg,
        toast_error_border = EXCLUDED.toast_error_border,
        toast_error_icon = EXCLUDED.toast_error_icon,
        toast_info_bg = EXCLUDED.toast_info_bg,
        toast_info_border = EXCLUDED.toast_info_border,
        toast_info_icon = EXCLUDED.toast_info_icon,
        toast_warning_bg = EXCLUDED.toast_warning_bg,
        toast_warning_border = EXCLUDED.toast_warning_border,
        toast_warning_icon = EXCLUDED.toast_warning_icon,
        chart_grid = EXCLUDED.chart_grid,
        chart_axis = EXCLUDED.chart_axis,
        chart_series_1 = EXCLUDED.chart_series_1,
        chart_series_2 = EXCLUDED.chart_series_2,
        chart_series_3 = EXCLUDED.chart_series_3,
        chart_series_4 = EXCLUDED.chart_series_4,
        chart_series_5 = EXCLUDED.chart_series_5,
        chart_series_6 = EXCLUDED.chart_series_6,
        chart_positive = EXCLUDED.chart_positive,
        chart_negative = EXCLUDED.chart_negative,
        chart_neutral = EXCLUDED.chart_neutral,
        display_name = EXCLUDED.display_name,
        email_sender_name = EXCLUDED.email_sender_name,
        email_sender_address = EXCLUDED.email_sender_address,
        custom_presets = EXCLUDED.custom_presets,
        logo_object_path = COALESCE(EXCLUDED.logo_object_path, tenant_branding.logo_object_path),
        updated_at = now()
    RETURNING *;
END;
$$;

REVOKE ALL ON FUNCTION public.tenant_branding_apply_patch(
    uuid, text, text, text, text, text, text, text, text, text, text,
    text, text, text, text, text, text, text, text, text, text, text, text, text, text, text,
    text, text, text, text, text, text, text, text, text, text, text, text, text, text, text,
    text, text, text, text, text, text, text, text, text, text, text, text, text, text, text,
    text, text, text, jsonb, text
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.tenant_branding_apply_patch(
    uuid, text, text, text, text, text, text, text, text, text, text,
    text, text, text, text, text, text, text, text, text, text, text, text, text, text, text,
    text, text, text, text, text, text, text, text, text, text, text, text, text, text, text,
    text, text, text, text, text, text, text, text, text, text, text, text, text, text, text,
    text, text, text, jsonb, text
) TO service_role;
